### ISSUE TITLE
Open cells by double clicking on a number

### ISSUE THREAD

**Issue by lolmaus** [scudco/tomsweeper#1]
When you have flagged as much mines near a number as the number, then it should be possible to reveal remaining unmarked cells by double clicking on that number.

![minesweeper](https://i.imgur.com/6zC3pBe.gif)

**Comment by sdhull** [comment]
huh I don't think I knew about this feature 😂

**Comment by scudco** [comment]
@lolmaus I just added support for this. Thanks for the suggestion. I'm mostly unfamiliar with all the interactions of the original so this was very helpful to learn :)
